// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy1hi2UALd1CdsJYvEX9xk6Wc46sWFxck',
    appId: '1:251441781427:web:f74dfc41741c212f07eec6',
    messagingSenderId: '251441781427',
    projectId: 'edu-mate12',
    authDomain: 'edu-mate12.firebaseapp.com',
    storageBucket: 'edu-mate12.firebasestorage.app',
    measurementId: 'G-NP92F1WGHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI8ya3anshxSdj8LZIEqOl7AxEyoaulxA',
    appId: '1:251441781427:android:1773c2289d1c6b5607eec6',
    messagingSenderId: '251441781427',
    projectId: 'edu-mate12',
    storageBucket: 'edu-mate12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq0IV9UfTRWUx4A_3pBEpKjaB1ifXgpkA',
    appId: '1:251441781427:ios:6774f71eefb6c86207eec6',
    messagingSenderId: '251441781427',
    projectId: 'edu-mate12',
    storageBucket: 'edu-mate12.firebasestorage.app',
    iosBundleId: 'com.example.eduMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq0IV9UfTRWUx4A_3pBEpKjaB1ifXgpkA',
    appId: '1:251441781427:ios:6774f71eefb6c86207eec6',
    messagingSenderId: '251441781427',
    projectId: 'edu-mate12',
    storageBucket: 'edu-mate12.firebasestorage.app',
    iosBundleId: 'com.example.eduMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy1hi2UALd1CdsJYvEX9xk6Wc46sWFxck',
    appId: '1:251441781427:web:b70cce3abcb4af5207eec6',
    messagingSenderId: '251441781427',
    projectId: 'edu-mate12',
    authDomain: 'edu-mate12.firebaseapp.com',
    storageBucket: 'edu-mate12.firebasestorage.app',
    measurementId: 'G-7EDLEW8DVT',
  );
}
